"""removendo reflexao do registro de valor

Revision ID: 25aa0dc2b08b
Revises: 49dcbad550f6
Create Date: 2025-11-26 14:09:30.850983

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "25aa0dc2b08b"
down_revision: Union[str, None] = "49dcbad550f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("registros_valor", "reflexao")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "registros_valor", sa.Column("reflexao", mysql.TEXT(), nullable=False)
    )
    # ### end Alembic commands ###
