"""Initial migration

Revision ID: 49dcbad550f6
Revises: 
Create Date: 2025-11-19 11:43:51.076174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49dcbad550f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciclos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('aberto', 'em_andamento', 'concluido', 'fechado', name='statusciclo'), nullable=True),
    sa.Column('etapa_atual', sa.Enum('escolha_pares', 'aprovacao_pares', 'avaliacoes', 'calibracao', 'feedback', name='etapaciclo'), nullable=True),
    sa.Column('data_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ciclos_id'), 'ciclos', ['id'], unique=False)
    op.create_table('colaboradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=255), nullable=True),
    sa.Column('departamento', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('nivel_carreira', sa.String(length=10), nullable=True),
    sa.Column('gestor_id', sa.Integer(), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['gestor_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colaboradores_email'), 'colaboradores', ['email'], unique=True)
    op.create_index(op.f('ix_colaboradores_google_id'), 'colaboradores', ['google_id'], unique=True)
    op.create_index(op.f('ix_colaboradores_id'), 'colaboradores', ['id'], unique=False)
    op.create_table('eixos_avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_eixos_avaliacao_id'), 'eixos_avaliacao', ['id'], unique=False)
    op.create_table('valores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('icone', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_valores_id'), 'valores', ['id'], unique=False)
    op.create_table('ciclos_avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ciclo_id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ciclo_id'], ['ciclos.id'], ),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ciclos_avaliacao_id'), 'ciclos_avaliacao', ['id'], unique=False)
    op.create_table('entregas_outstanding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('impacto', sa.Text(), nullable=False),
    sa.Column('evidencias', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entregas_outstanding_id'), 'entregas_outstanding', ['id'], unique=False)
    op.create_table('niveis_eixo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eixo_id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['eixo_id'], ['eixos_avaliacao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_niveis_eixo_id'), 'niveis_eixo', ['id'], unique=False)
    op.create_table('registros_valor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('reflexao', sa.Text(), nullable=False),
    sa.Column('impacto', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_valor_id'), 'registros_valor', ['id'], unique=False)
    op.create_table('avaliacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ciclo_id', sa.Integer(), nullable=False),
    sa.Column('ciclo_avaliacao_id', sa.Integer(), nullable=True),
    sa.Column('avaliador_id', sa.Integer(), nullable=False),
    sa.Column('avaliado_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('autoavaliacao', 'par', 'gestor', name='tipoavaliacao'), nullable=False),
    sa.Column('avaliacao_geral', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['avaliado_id'], ['colaboradores.id'], ),
    sa.ForeignKeyConstraint(['avaliador_id'], ['colaboradores.id'], ),
    sa.ForeignKeyConstraint(['ciclo_avaliacao_id'], ['ciclos_avaliacao.id'], ),
    sa.ForeignKeyConstraint(['ciclo_id'], ['ciclos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avaliacoes_id'), 'avaliacoes', ['id'], unique=False)
    op.create_table('pares_selecionados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ciclo_avaliacao_id', sa.Integer(), nullable=False),
    sa.Column('par_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ciclo_avaliacao_id'], ['ciclos_avaliacao.id'], ),
    sa.ForeignKeyConstraint(['par_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pares_selecionados_id'), 'pares_selecionados', ['id'], unique=False)
    op.create_table('registro_valor_association',
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('valor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['registro_id'], ['registros_valor.id'], ),
    sa.ForeignKeyConstraint(['valor_id'], ['valores.id'], ),
    sa.PrimaryKeyConstraint('registro_id', 'valor_id')
    )
    op.create_table('avaliacoes_eixos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avaliacao_id', sa.Integer(), nullable=False),
    sa.Column('eixo_id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacoes.id'], ),
    sa.ForeignKeyConstraint(['eixo_id'], ['eixos_avaliacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avaliacoes_eixos_id'), 'avaliacoes_eixos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avaliacoes_eixos_id'), table_name='avaliacoes_eixos')
    op.drop_table('avaliacoes_eixos')
    op.drop_table('registro_valor_association')
    op.drop_index(op.f('ix_pares_selecionados_id'), table_name='pares_selecionados')
    op.drop_table('pares_selecionados')
    op.drop_index(op.f('ix_avaliacoes_id'), table_name='avaliacoes')
    op.drop_table('avaliacoes')
    op.drop_index(op.f('ix_registros_valor_id'), table_name='registros_valor')
    op.drop_table('registros_valor')
    op.drop_index(op.f('ix_niveis_eixo_id'), table_name='niveis_eixo')
    op.drop_table('niveis_eixo')
    op.drop_index(op.f('ix_entregas_outstanding_id'), table_name='entregas_outstanding')
    op.drop_table('entregas_outstanding')
    op.drop_index(op.f('ix_ciclos_avaliacao_id'), table_name='ciclos_avaliacao')
    op.drop_table('ciclos_avaliacao')
    op.drop_index(op.f('ix_valores_id'), table_name='valores')
    op.drop_table('valores')
    op.drop_index(op.f('ix_eixos_avaliacao_id'), table_name='eixos_avaliacao')
    op.drop_table('eixos_avaliacao')
    op.drop_index(op.f('ix_colaboradores_id'), table_name='colaboradores')
    op.drop_index(op.f('ix_colaboradores_google_id'), table_name='colaboradores')
    op.drop_index(op.f('ix_colaboradores_email'), table_name='colaboradores')
    op.drop_table('colaboradores')
    op.drop_index(op.f('ix_ciclos_id'), table_name='ciclos')
    op.drop_table('ciclos')
    # ### end Alembic commands ###

