"""adicionar status_aprovacao em entregas_outstanding

Revision ID: 9d96c2094637
Revises: 0e166f7d1677
Create Date: 2026-01-08 18:02:14.167502

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from app.models.entrega_outstanding import StatusAprovacao
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "9d96c2094637"
down_revision: Union[str, None] = "0e166f7d1677"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "avaliacoes",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.alter_column(
        "avaliacoes",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.alter_column(
        "avaliacoes_eixos",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.alter_column(
        "avaliacoes_eixos",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.alter_column(
        "avaliacoes_gestor",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.alter_column(
        "avaliacoes_gestor",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.alter_column(
        "avaliacoes_gestor_respostas",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.alter_column(
        "avaliacoes_gestor_respostas",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.alter_column(
        "ciclos",
        "data_inicio",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.alter_column(
        "ciclos",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.alter_column(
        "ciclos",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.alter_column(
        "ciclos_avaliacao",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.alter_column(
        "ciclos_avaliacao",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.alter_column(
        "colaboradores",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.alter_column(
        "colaboradores",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.add_column(
        "entregas_outstanding",
        sa.Column(
            "status_aprovacao",
            sa.String(length=20),
            nullable=False,
            server_default=StatusAprovacao.PENDENTE.value,
        ),
    )
    op.add_column(
        "entregas_outstanding",
        sa.Column("aprovado_por_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "entregas_outstanding",
        sa.Column("aprovado_em", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "entregas_outstanding",
        sa.Column("observacao_aprovacao", sa.Text(), nullable=True),
    )
    op.alter_column(
        "entregas_outstanding",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.alter_column(
        "entregas_outstanding",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.create_foreign_key(
        None, "entregas_outstanding", "colaboradores", ["aprovado_por_id"], ["id"]
    )
    op.alter_column(
        "feedback_liberacao",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.alter_column(
        "feedback_liberacao",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.alter_column(
        "pares_selecionados",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.alter_column(
        "registros_valor",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    op.alter_column(
        "registros_valor",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "registros_valor",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "registros_valor",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "pares_selecionados",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "feedback_liberacao",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "feedback_liberacao",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.drop_constraint(None, "entregas_outstanding", type_="foreignkey")
    op.alter_column(
        "entregas_outstanding",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "entregas_outstanding",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.drop_column("entregas_outstanding", "observacao_aprovacao")
    op.drop_column("entregas_outstanding", "aprovado_em")
    op.drop_column("entregas_outstanding", "aprovado_por_id")
    op.drop_column("entregas_outstanding", "status_aprovacao")
    op.alter_column(
        "colaboradores",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "colaboradores",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "ciclos_avaliacao",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "ciclos_avaliacao",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "ciclos",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "ciclos",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "ciclos",
        "data_inicio",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "avaliacoes_gestor_respostas",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "avaliacoes_gestor_respostas",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "avaliacoes_gestor",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "avaliacoes_gestor",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "avaliacoes_eixos",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "avaliacoes_eixos",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "avaliacoes",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "avaliacoes",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
