"""criando avaliação do gestor

Revision ID: a35c221daffa
Revises: 25aa0dc2b08b
Create Date: 2025-12-04 19:57:26.159106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a35c221daffa'
down_revision: Union[str, None] = '25aa0dc2b08b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacoes_gestor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ciclo_id', sa.Integer(), nullable=False),
    sa.Column('ciclo_avaliacao_id', sa.Integer(), nullable=True),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('gestor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ciclo_avaliacao_id'], ['ciclos_avaliacao.id'], ),
    sa.ForeignKeyConstraint(['ciclo_id'], ['ciclos.id'], ),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.ForeignKeyConstraint(['gestor_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avaliacoes_gestor_id'), 'avaliacoes_gestor', ['id'], unique=False)
    op.create_table('avaliacoes_gestor_respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avaliacao_id', sa.Integer(), nullable=False),
    sa.Column('pergunta_codigo', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('resposta_escala', sa.Integer(), nullable=True),
    sa.Column('resposta_texto', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacoes_gestor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avaliacoes_gestor_respostas_id'), 'avaliacoes_gestor_respostas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avaliacoes_gestor_respostas_id'), table_name='avaliacoes_gestor_respostas')
    op.drop_table('avaliacoes_gestor_respostas')
    op.drop_index(op.f('ix_avaliacoes_gestor_id'), table_name='avaliacoes_gestor')
    op.drop_table('avaliacoes_gestor')
    # ### end Alembic commands ###

